# Epic DB
FROM docker.kyck.com/kyck/elixir
MAINTAINER Brandon Dennis "dennis@kyck.com"
ENV REFRESHED_AT 2015-02-21
ENV MIX_ENV test

WORKDIR /var/apps/epic_db

ADD mix.exs mix.exs
ADD mix.lock mix.lock

RUN mix deps.get && \
    mix deps.compile

ADD config config
ADD lib lib

RUN mix compile

ADD test test

